use std::env;
use std::fs::File;
use std::io::{stdout, Write};
use std::process::{Command, ExitCode};
use std::time::SystemTime;

use anyhow::{anyhow, Result};
use chrono::Local;

fn main() -> Result<ExitCode> {
    let mut args = env::args();
    if args.len() != 3 {
        return Err(anyhow!("expected: gen-version-id op dest_path"));
    }

    let op = args.nth(1).unwrap();
    let dest_path = args.next().unwrap();

    match op.as_str() {
        "gen" => {
            do_gen(dest_path.as_str())?;
        }
        "touch" => {
            do_touch(dest_path.as_str())?;
        }
        _ => {
            return Err(anyhow!("unsupported op"));
        }
    }

    Ok(ExitCode::SUCCESS)
}

fn do_gen(dest_path: &str) -> Result<()> {
    let output = Command::new("git")
        .arg("describe")
        .arg("--all")
        .arg("--long")
        .arg("--always")
        .arg("--dirty")
        .output();

    let git_desc = match output {
        Ok(output) => {
            if output.status.success() {
                String::from_utf8(output.stdout)?.trim_end_matches('\n').to_string()
            } else {
                stdout().write_all(&output.stderr)?;
                String::from("none")
            }
        }
        Err(e) => {
            println!("{}", e);
            String::from("none")
        }
    };
    println!("git_desc: {}", git_desc);

    let now = Local::now();
    let datetime_fmt = now.format("%Y%m%d_%H%M%S").to_string();
    println!("datetime: {}", datetime_fmt);

    {
        let mut file = File::create(dest_path)?;
        writeln!(&mut file, "// DO NOT EDIT. Auto-generated by gen-version-id.")?;
        writeln!(&mut file, "#pragma once")?;
        writeln!(&mut file, "namespace v1336::core {{")?;
        writeln!(&mut file, "inline constexpr const char* VERSION_ID = \"{}-{}\";", git_desc, datetime_fmt)?;
        writeln!(&mut file, "}}")?;
    }

    Ok(())
}

fn do_touch(dest_path: &str) -> Result<()> {
    let file = File::options().write(true).open(dest_path);

    if let Ok(file) = file {
        let now = SystemTime::now();
        file.set_modified(now)?;
    }

    Ok(())
}
