use std::{env, fs, fs::File};
use std::io::{stdout, Write};
use std::path::Path;
use std::process::{Command, ExitCode};
use std::time::SystemTime;

use anyhow::{anyhow, Result};
use chrono::Local;

fn main() -> Result<ExitCode> {
    let mut args = env::args();
    if args.len() < 3 {
        return Err(anyhow!("expected: gen-version-id op dest_path [proj_path]"));
    }

    let op = args.nth(1).unwrap();
    let dest_path = args.next().unwrap();
    let proj_path = args.next();

    match op.as_str() {
        "gen" => {
            do_gen(proj_path.as_deref(), &dest_path)?;
        }
        "touch" => {
            do_touch(&dest_path)?;
        }
        _ => {
            return Err(anyhow!("unsupported op"));
        }
    }

    Ok(ExitCode::SUCCESS)
}

fn do_gen<P1, P2>(proj_path: Option<P1>, dest_path: P2) -> Result<()>
where
    P1: AsRef<Path>,
    P2: AsRef<Path>,
{
    let output = Command::new("git")
        .arg("describe")
        .arg("--all")
        .arg("--long")
        .arg("--always")
        .arg("--dirty")
        .output();

    let git_desc = match output {
        Ok(output) => {
            if output.status.success() {
                Some(String::from_utf8(output.stdout)?.trim_end_matches('\n').to_string())
            } else {
                let _ = stdout().write_all(&output.stderr);
                None
            }
        }
        Err(e) => {
            println!("{}", e);
            None
        }
    };
    //println!("git_desc: {:?}", git_desc);

    let git_id = git_desc
        .or_else(|| {
            proj_path.and_then(|x| {
                match fs::canonicalize(x) {
                    Ok(norm) => {
                        if let Some(dir) = norm.file_name() {
                            Some(dir.to_string_lossy().into_owned())
                        } else {
                            None
                        }
                    }
                    Err(e) => {
                        println!("{}", e);
                        None
                    }
                }
            })
        })
        .unwrap_or(String::from("none"));
    println!("git_id: {:?}", git_id);

    let now = Local::now();
    let datetime_fmt = now.format("%Y%m%d_%H%M%S").to_string();
    println!("datetime: {}", datetime_fmt);

    {
        let mut file = File::create(dest_path)?;
        writeln!(&mut file, "// DO NOT EDIT. Auto-generated by gen-version-id.")?;
        writeln!(&mut file, "#pragma once")?;
        writeln!(&mut file, "namespace v1336::core {{")?;
        writeln!(&mut file, "inline constexpr const char* VERSION_ID = \"{}-{}\";", git_id, datetime_fmt)?;
        writeln!(&mut file, "}}")?;
    }

    Ok(())
}

fn do_touch<P: AsRef<Path>>(dest_path: P) -> Result<()> {
    let file = File::options().write(true).open(dest_path);

    if let Ok(file) = file {
        let now = SystemTime::now();
        file.set_modified(now)?;
    }

    Ok(())
}
